<a href="https://colab.research.google.com/github/lamunushannie/Salary-Prediction-Using-Machine-Learning/blob/main/Salary_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from google.colab import drive
drive.mount('/content/drive')
from sklearn import linear_model

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [36]:
df = pd.read_csv("/content/drive/MyDrive/hiring (1).csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df.columns = ['experience', 'test_score', 'interview_score', 'salary']
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [27]:
word_to_num = {
    'zero':0, 'one':1, 'two':2, 'three':3, 'four':4,
    'five':5, 'six':6, 'seven':7, 'eight':8,
    'nine':9, 'ten':10, 'eleven':11, 'twelve':12
}
df['experience'] = df['experience'].replace(word_to_num)
df['experience'] = pd.to_numeric(df['experience'], errors='coerce')
df

experience  test_score  interview_score  salary
0         0.0    8.000000                9   50000
1         0.0    8.000000                6   45000
2         5.0    6.000000                7   60000
3         2.0   10.000000               10   65000
4         7.0    9.000000                6   70000
5         3.0    7.000000               10   62000
6        10.0    7.857143                7   72000
7        11.0    7.000000                8   80000

In [7]:
df['experience'] = df['experience'].fillna(0)
df['test_score'] = df['test_score'].fillna(df['test_score'].mean())
df['interview_score'] = df['interview_score'].fillna(df['interview_score'].mean())
df

experience  test_score  interview_score  salary
0         0.0    8.000000                9   50000
1         0.0    8.000000                6   45000
2         5.0    6.000000                7   60000
3         2.0   10.000000               10   65000
4         7.0    9.000000                6   70000
5         3.0    7.000000               10   62000
6        10.0    7.857143                7   72000
7        11.0    7.000000                8   80000

In [10]:
# Prepare features and target
X = df[['experience', 'test_score', 'interview_score']]
y = df['salary']
df

experience  test_score  interview_score  salary
0         0.0    8.000000                9   50000
1         0.0    8.000000                6   45000
2         5.0    6.000000                7   60000
3         2.0   10.000000               10   65000
4         7.0    9.000000                6   70000
5         3.0    7.000000               10   62000
6        10.0    7.857143                7   72000
7        11.0    7.000000                8   80000

In [25]:
reg.score(X, y)

0.9639958361860579

In [17]:
reg = linear_model.LinearRegression()
reg.fit(X, y)

LinearRegression()

In [18]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [19]:
reg.intercept_

np.float64(17237.330313727172)

In [30]:
#predict salaries for  candidates, 2 yr experience, 9 test score, 6 interview score
reg.predict([[2, 9, 6]])

array([53290.89255945])

In [32]:
#predict salaries for  candidates, 12 yr experience, 10 test score, 10 interview score
reg.predict([[12, 10, 10]])

array([92268.07227784])